controllers:
    resource: ../src/Controller/
    type: attribute

# routes.yaml

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_login_check:
    path: /login_check
